### ISSUE TITLE
Drag few lines

### ISSUE THREAD

**Issue by Pitometsu** [rejeep/drag-stuff.el#12]
When I select few lines, it dragged together with adjacent bottom one.

**Comment by rejeep** [comment]
I don't understand the question?

**Comment by Pitometsu** [comment]
When select few lines by region, and drag up/down the bottom one, not marked, drag with them.

**Comment by rejeep** [comment]
I guess your point is at the beginning of that line? That's by design. I like to move whole blocks instead of what just mark. Just place your point in the middle of the line above and drag instead.
