### ISSUE TITLE
Global Drag Stuff Mode

### ISSUE THREAD

**Issue by egarrulo** [rejeep/drag-stuff.el#14]
Dear Mr Andersson,

thank you for sharing this useful package.

It seem to me that Drag Stuff Mode is not global, because I have added this lines to my `.emacs`:

    (require 'drag-stuff)
    (drag-stuff-mode t)

But I still have to enable Drag Stuff Mode manually.  Unless I am doing something wrong, would you please consider making Drag Stuff Mode a global minor mode?

Thanks for your attention.
Best Regards

**Comment by egarrulo** [comment]
Sorry, I didn't know about `drag-stuff-global-mode` because it wasn't mentioned in the README (I learned about it by reading a comment elsewhere about Drag Stuff).  Sorry for the inconvenience.

**Comment by rejeep** [comment]
Thanks, I added a note about the global mode in the REAMDE.
