### ISSUE TITLE
Can't set 'super key as drag-stuff-modifier

### ISSUE THREAD

**Issue by kaliif** [rejeep/drag-stuff.el#19]
The default 'meta works fine, so does setting 'control or 'shift. Setting 'super however binds the commands to shift+super. A bit unexpected. I'd like to be able to use 'super alone.

**Comment by rejeep** [comment]
Do you set `drag-stuff-modifier` to simply `super` and it somehow adds shift you mean? Either way, you can simply just bind whatever key you want using `global-set-key/define-key`.

**Comment by kaliif** [comment]
Yes. The line I'm using to set super is:

(setq drag-stuff-modifier 'super)

and I end up with S-s-arrow keybindings

Actually after posting I discovered that this could be some idiosyncrasy of my system, I'm not able to set s-<up> anywhere else either. But in such cases the keybinding simply doesn't work not set itself to shift+super. Not sure where to go with this..

**Comment by rejeep** [comment]
I have never used a super key, so I cant help you. Closing this as it's not a drag-stuff issue.
