### ISSUE TITLE
drag stuff with multiple cursors

### ISSUE THREAD

**Issue by nikadon** [rejeep/drag-stuff.el#23]
drag-stuff is brilliant :) 
unfortunately for two cursors in two consequent lines (line n and n+1) it only works upwards (dragging towards bottom has no effect). It works with no hassle in both directions when the two cursors are separated with at least one line that has no cursor in it...

**Comment by rejeep** [comment]
Are you talking about multiple cursors? Drag stuff does not support it, I don't have time to implement support for it, but if you are willing to implement it yourself, I will be happy to merge it!

**Comment by nikadon** [comment]
Well, it kinda supports it with occasional glitches, I might be able to spare some time in December to level-up in lisp and that would be a good playground :)
