### ISSUE TITLE
drag-left and drag-right clobber Emacs / Readline word-left/right defaults.

### ISSUE THREAD

**Issue by jasonm23** [rejeep/drag-stuff.el#7]
The up/down functionality is very useful, but `M-left` / `M-right` are Readline / Emacs default binding, so the drag-left and drag-right on those bindings is extremely unwelcome.

I suggest they are re-bound to keep them out of default bindings.

Users can easily override Emacs defaults themselves if they want to use them in this way.

**Comment by Froziph** [comment]
Did this ever become a thing :P?

**Comment by jasonm23** [comment]
I'll need to do it still.  I have a move up down extension which I put together years ago so I personally use that one still.

My initial motivation was to help other people adopt yours.

I'm not seeing anyone else complain about these keys, so it's a theoretical problem, as opposed to a pressing issue.

I wonder how many people are using this? 

(Note OS X maps the meta-left / right to move cursor left / right word too, so imagine wider adoption for those users will pop this issue again.)

**Comment by emilv** [comment]
I do have this problem (on OSX as you guessed). Moving left only moves the word, not the cursor. All I really want is moving up and down. I guess I can try to avoid  left/right entirely but it would be nice to disable the functionality.

**Comment by rejeep** [comment]
I'm closing this and if this is a big enough issue, please open a pull request with the solution decided on above.
